# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- release

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: 'Release'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: 'Release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(buildPlatform)\Release'
    ArtifactName: 'releasedrop'
    publishLocation: 'Container'

- task: CmdLine@2
  inputs:
    script: |
      dir
      git clone https://16TWindsor:dfabrA6e@github.com/16TWindsor/mastermind.git
      copy * mastermind\
      cd mastermind
      dir
      git config --global user.email "16TWindsor@calderlearningtrust.com"
      git config --global user.name "16TWindsor"
      git add *
      git commit -m "Release Source Code"
      git push